[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Comrade = "99d987ce-9a1e-4df8-bc0b-1ea019aa547b"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pyehtim = "3d61700d-6e5b-419a-8e22-9c066cf00468"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
VLBIImagePriors = "b1ba175b-8447-452c-b961-7db2d6f7a029"

[compat]
CairoMakie = "0.12"
Distributions = "0.25"
Optimization = "4"
Pigeons = "0.4"
Plots = "1"
Pyehtim = "0.1"
StableRNGs = "1"
VLBIImagePriors = "0.8"
