[deps]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Comrade = "99d987ce-9a1e-4df8-bc0b-1ea019aa547b"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pyehtim = "3d61700d-6e5b-419a-8e22-9c066cf00468"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
VLBIImagePriors = "b1ba175b-8447-452c-b961-7db2d6f7a029"

[compat]
CairoMakie = "0.13"
Distributions = "0.25"
Optimization = "4"
Pkg = "1"
Pyehtim = "0.2"
StableRNGs = "1"
VLBIImagePriors = "0.10"
